
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: picture_development
  username: alexanderbatalov
  password: 

test:
  <<: *default
  database: picture_test
  username: alexanderbatalov
  password: 

production:
  <<: *default
  database: picture_production
  username: picture
  password: <%= ENV['PICTURE_DATABASE_PASSWORD'] %>
